#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: auth-service
  internal-api-key: ${INTERNAL_API_KEY}

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: never
